### ISSUE TITLE
Error when first setup

### ISSUE THREAD

**Issue by TUCAOEVER** [SkytAsul/CitizensText#7]
[11:13:14] [Server thread/INFO]: [CitizensText] Disabling CitizensText v1.19.5
[11:13:14] [Server thread/ERROR]: Error occurred while disabling CitizensText v1.19.5 (Is it up to date?)
java.lang.NullPointerException: null
	at fr.skytasul.citizenstext.CitizensText.saveDatas(CitizensText.java:147) ~[?:?]
	at fr.skytasul.citizenstext.CitizensText.disable(CitizensText.java:76) ~[?:?]
	at fr.skytasul.citizenstext.CitizensText.onDisable(CitizensText.java:70) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:406) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:750) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:753) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:1017) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Kichura** [comment]
Update plugin to newest CI build and try again.
